CREATE TABLESPACE lob_tablespace
    DATAFILE 'lob_datafile.dbf' SIZE 100M
    AUTOEXTEND ON NEXT 10M
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE OR REPLACE DIRECTORY LOB_DOCUMENTS_DIR AS 'D:/BD';

create user lob_user IDENTIFIED by 1234;
ALTER SESSION SET "_oracle_script" = TRUE;

GRANT CONNECT TO lob_user;
GRANT RESOURCE TO lob_user;
GRANT CREATE SESSION TO lob_user;
GRANT EXECUTE ON DBMS_LOB TO lob_user;
GRANT UNLIMITED TABLESPACE TO lob_user;
GRANT READ, WRITE ON DIRECTORY LOB_DOCUMENTS_DIR TO lob_user;
GRANT CREATE PROCEDURE TO lob_user;

ALTER USER lob_user QUOTA UNLIMITED ON lob_tablespace;


CREATE TABLE BLOB_TABLE
(
    ID   INT PRIMARY KEY,
    FOTO BLOB DEFAULT EMPTY_BLOB(),
    DOC  BFILE
);

select * from BLOB_TABLE;
--добалвение
INSERT INTO BLOB_TABLE (id, foto, doc)
        VALUES (1, BFILENAME('LOB_DOCUMENTS_DIR', 'podobed.jpg'), BFILENAME('LOB_DOCUMENTS_DIR', 'document1.pdf'));
COMMIT;
-- изменение 
UPDATE BLOB_TABLE
SET FOTO = BFILENAME('LOB_DOCUMENTS_DIR', 'podobed.jpg'),
    DOC = BFILENAME('LOB_DOCUMENTS_DIR', 'document2.pdf') 
WHERE ID = 1;
commit;
--удаление
DELETE FROM BLOB_TABLE
WHERE ID = 1;
COMMIT;