CREATE TABLESPACE TS_CARS
    DATAFILE 'C:\oracle\tablespaces\transportation\TS_CARS.dbf'
    SIZE 5m
    AUTOEXTEND ON NEXT 5m MAXSIZE 100m
    ONLINE;

CREATE TABLESPACE TS_ORDERS
    DATAFILE 'C:\oracle\tablespaces\transportation\TS_ORDERS.dbf'
    SIZE 10m
    AUTOEXTEND ON NEXT 10m MAXSIZE 300m
    ONLINE;

ALTER USER TRANSPORT_ADMIN QUOTA UNLIMITED ON TS_CARS;
ALTER USER TRANSPORT_ADMIN QUOTA UNLIMITED ON TS_ORDERS;

GRANT CREATE ANY TABLE TO TRANSPORT_ADMIN;

GRANT SYSDBA TO TRANSPORT_ADMIN;


CREATE TABLE BRAND
(
    ID         INT GENERATED ALWAYS AS IDENTITY (START WITH 1 NOCACHE),
    BRAND_NAME NVARCHAR2(40) NOT NULL,

    CONSTRAINT PK_BRAND_ID PRIMARY KEY (ID)
) 

CREATE TABLE COLOR
(
    ID         INT GENERATED ALWAYS AS IDENTITY (START WITH 1 NOCACHE),
    COLOR_NAME NVARCHAR2(20) NOT NULL,

    CONSTRAINT PK_COLOR_ID PRIMARY KEY (ID)
) 


CREATE TABLE CAR
(
    REGISTRATION_NUM INT GENERATED ALWAYS AS IDENTITY (START WITH 1 CACHE 2),
    BRAND_ID         INT,
    MODEL            VARCHAR2(20) NOT NULL,
    YEAR             DATE         NOT NULL,
    COLOR_ID         INT,


    CONSTRAINT PK_REGISTRATION_NUM
        PRIMARY KEY (REGISTRATION_NUM),
    CONSTRAINT FK_CAR_BRAND_ID FOREIGN KEY (BRAND_ID)
        REFERENCES BRAND (ID) ON DELETE SET NULL,
    CONSTRAINT FK_CAR_COLOR_ID FOREIGN KEY (COLOR_ID)
        REFERENCES COLOR (ID) ON DELETE SET NULL
) 

CREATE TABLE DRIVER
(
    ID           INT GENERATED ALWAYS AS IDENTITY (START WITH 1 CACHE 2),
    NAME         NVARCHAR2(40) NOT NULL,
    SURNAME      NVARCHAR2(40),
    LICENSE      INT           NOT NULL,
    PHONE_NUMBER VARCHAR2(20)  NOT NULL,
    EMAIL        NVARCHAR2(50) NOT NULL,

    CONSTRAINT PK_DRIVER_ID
        PRIMARY KEY (ID)
) 

CREATE TABLE DRIVER_CAR
(
    DRIVER_ID INT NOT NULL,
    CAR_ID    INT NOT NULL,
    "DATE" DATE DEFAULT SYSDATE,

    CONSTRAINT FK_DRIVER_CAR_DRIVER_ID FOREIGN KEY (DRIVER_ID)
        REFERENCES DRIVER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_DRIVER_CAR_CAR_ID FOREIGN KEY (CAR_ID)
        REFERENCES CAR (REGISTRATION_NUM) ON DELETE CASCADE
)

CREATE TABLE STATUS
(
    ID     INT GENERATED ALWAYS AS IDENTITY (START WITH 1 NOCACHE),
    STATUS NVARCHAR2(16) NOT NULL,

    CONSTRAINT PK_STATUS_ID PRIMARY KEY (ID)
) 

CREATE TABLE CLIENT
(
    ID           INT GENERATED ALWAYS AS IDENTITY (START WITH 1 CACHE 2),
    NAME         NVARCHAR2(40)  NOT NULL,
    SURNAME      NVARCHAR2(40)  NOT NULL,
    ADDRESS      NVARCHAR2(100) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    EMAIL        NVARCHAR2(50),

    CONSTRAINT PK_CLIENT_ID
        PRIMARY KEY (ID),
    CONSTRAINT CK_CLIENT_CONTACT_NOT_NULL
        CHECK ( PHONE_NUMBER IS NOT NULL OR EMAIL IS NOT NULL )
) 

CREATE TABLE "ORDER"
(
    ID          INT GENERATED ALWAYS AS IDENTITY (START WITH 1 CACHE 2),
    CLIENT_ID   INT,
    DRIVER_ID   INT,
    INFO        NVARCHAR2(300),
    DATETIME    DATE DEFAULT SYSDATE,
    COST        FLOAT          NOT NULL,
    STATUS      INT,
    DESTINATION NVARCHAR2(100) NOT NULL,
    ARRIVAL     NVARCHAR2(100) NOT NULL,

    CONSTRAINT FK_ORDER_CLIENT_ID FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT (ID) ON DELETE SET NULL,
    CONSTRAINT FK_ORDER_DRIVER_ID FOREIGN KEY (DRIVER_ID)
        REFERENCES DRIVER (ID) ON DELETE SET NULL,
    CONSTRAINT FK_ORDER_STATUS_ID FOREIGN KEY (STATUS)
        REFERENCES STATUS (ID) ON DELETE SET NULL,
    CONSTRAINT PK_ORDER_ID PRIMARY KEY (ID)
) 

CREATE TABLE REVIEW
(
    ORDER_ID INT            NOT NULL,
    TEXT     NVARCHAR2(500) NOT NULL,
    STARS    INT            NOT NULL,

    CONSTRAINT FK_REVIEW_ORDER_ID FOREIGN KEY (ORDER_ID)
        REFERENCES "ORDER" (ID),
    CONSTRAINT PK_REVIEW_ORDER_ID PRIMARY KEY (ORDER_ID),
    CONSTRAINT CK_REVIEW_STARS_RANGE CHECK ( STARS > 0 AND STARS <= 10)
) 
