
USE TRANSPORTATION
-- Примеры INSERT для таблицы "BRAND"
INSERT INTO BRAND (BRAND_NAME) VALUES ('Ford');
INSERT INTO BRAND (BRAND_NAME) VALUES ('Chevrolet');
INSERT INTO BRAND (BRAND_NAME) VALUES ('Toyota');


-- Примеры INSERT для таблицы "COLOR"
INSERT INTO COLOR (COLOR_NAME) VALUES ('Blue');
INSERT INTO COLOR (COLOR_NAME) VALUES ('Black');
INSERT INTO COLOR (COLOR_NAME) VALUES ('Red');


-- Примеры INSERT для таблицы "CAR"
INSERT INTO CAR (BRAND_ID, MODEL, YEAR, COLOR_ID, CAPACITY) VALUES (1, 'Mustang', CAST('2022-01-01' AS DATE), 2,20);
INSERT INTO CAR (BRAND_ID, MODEL, YEAR, COLOR_ID, CAPACITY) VALUES (2, 'Camaro', CAST('2023-07-21' AS DATE), 1,30);
INSERT INTO CAR (BRAND_ID, MODEL, YEAR, COLOR_ID, CAPACITY) VALUES (1, 'Camry', CAST('2023-11-06' AS DATE), 3,40);


-- Примеры INSERT для таблицы "DRIVER"
INSERT INTO DRIVER (NAME, SURNAME, LICENSE, PHONE_NUMBER, EMAIL,MANAGER_HIERARCHY) VALUES ('Michael', 'Johnson', 987654321, '555-123-4567', 'michael@example.com',hierarchyid::Parse('/'));
INSERT INTO DRIVER (NAME, SURNAME, LICENSE, PHONE_NUMBER, EMAIL,MANAGER_HIERARCHY) VALUES ('Emily', 'Anderson', 654321987, '555-987-6543', 'emily@example.com',hierarchyid::Parse('/1/1/'));
INSERT INTO DRIVER (NAME, SURNAME, LICENSE, PHONE_NUMBER, EMAIL,MANAGER_HIERARCHY) VALUES ('John', 'Doe', 123456789, '123-456-7890', 'johndoe@example.com',hierarchyid::Parse('/1/1/1/'));
select * from DRIVER;


-- Примеры INSERT для таблицы "DRIVER_CAR"
INSERT INTO DRIVER_CAR (DRIVER_ID, CAR_ID, [DATE]) VALUES (1, 1, CAST('2023-10-10' AS DATE));
INSERT INTO DRIVER_CAR (DRIVER_ID, CAR_ID, [DATE]) VALUES (2, 2, CAST('2023-10-10' AS DATE));
INSERT INTO DRIVER_CAR (DRIVER_ID, CAR_ID, [DATE]) VALUES (3, 3, CAST('2023-10-10' AS DATE));
INSERT INTO DRIVER_CAR (DRIVER_ID, CAR_ID, [DATE]) VALUES (1, 3, CAST('2023-10-09' AS DATE));
INSERT INTO DRIVER_CAR (DRIVER_ID, CAR_ID, [DATE]) VALUES (2, 1, CAST('2023-10-09' AS DATE));
INSERT INTO DRIVER_CAR (DRIVER_ID, CAR_ID, [DATE]) VALUES (3, 2, CAST('2023-10-09' AS DATE));

-- Примеры INSERT для таблицы "CLIENT"
INSERT INTO CLIENT (NAME, SURNAME, ADDRESS, PHONE_NUMBER, EMAIL) VALUES ('Robert', 'Brown', '456 Oak St', '555-789-1234', 'robert@example.com');
INSERT INTO CLIENT (NAME, SURNAME, ADDRESS, PHONE_NUMBER, EMAIL) VALUES ('Sophia', 'Davis', '789 Pine Ave', '555-456-7890', 'sophia@example.com');
INSERT INTO CLIENT (NAME, SURNAME, ADDRESS, PHONE_NUMBER, EMAIL) VALUES ('Jane', 'Smith', '123 Main St', '987-654-3210', 'janesmith@example.com');


-- Примеры INSERT для таблицы "ORDER"
INSERT INTO [ORDER] (CLIENT_ID, DRIVER_ID, INFO, COST, DESTINATION, ARRIVAL) VALUES (1, 1, 'Additional info for order 1', 150.0, 2, '789 Maple Ln', '123 Oak St');
INSERT INTO [ORDER] (CLIENT_ID, DRIVER_ID, INFO, COST, DESTINATION, ARRIVAL) VALUES (2, 2, 'Additional info for order 2', 200.0, 1, '456 Elm St', '789 Pine Ave');
INSERT INTO [ORDER] (CLIENT_ID, DRIVER_ID, INFO, COST, DESTINATION, ARRIVAL) VALUES (3, 1, 'Some additional information', 100.0, 1, '123 Park Ave', '456 Elm St');




-- Примеры INSERT для таблицы "REVIEW"
INSERT INTO REVIEW (ORDER_ID, TEXT, STARS) VALUES (1, 'Excellent service!',9);
INSERT INTO REVIEW (ORDER_ID, TEXT, STARS) VALUES (2, 'Average service.', 5);
INSERT INTO REVIEW (ORDER_ID, TEXT, STARS) VALUES (3, 'Great service!', 7);