
USE TRANSPORTATION;
GO
SELECT * FROM dbo.CAR;

go
CREATE VIEW VW_CAR AS
SELECT c.REGISTRATION_NUM, b.BRAND_NAME AS BRAND, col.COLOR_NAME AS COLOR, c.MODEL, c.YEAR
FROM CAR c
INNER JOIN BRAND b ON c.BRAND_ID = b.ID
INNER JOIN COLOR col ON c.COLOR_ID = col.ID;

go
CREATE OR ALTER VIEW VW_DRIVER_CAR AS
SELECT dc.DRIVER_ID, d.NAME AS DRIVER_NAME, dc.CAR_ID, c.MODEL
FROM DRIVER_CAR dc
INNER JOIN DRIVER d ON dc.DRIVER_ID = d.ID
INNER JOIN CAR c ON dc.CAR_ID = c.REGISTRATION_NUM;

go
CREATE OR ALTER VIEW VW_ORDER AS
SELECT o.ID, o.DATETIME, o.COST,
       c.NAME AS CLIENT_NAME, c.EMAIL AS CLIENT_EMAIL,
       dr.NAME AS DRIVER_NAME, dr.PHONE_NUMBER AS DRIVER_NUMBER,
       car.REGISTRATION_NUM AS REG_NUM, car.BRAND, car.MODEL, car.COLOR
FROM [ORDER] o
INNER JOIN CLIENT c ON o.CLIENT_ID = c.ID
INNER JOIN DRIVER dr ON o.DRIVER_ID = dr.ID
INNER JOIN DRIVER_CAR dr_car ON dr_car.DRIVER_ID = dr.ID AND CONVERT(DATE, dr_car."DATE") = CONVERT(DATE, o.DATETIME)
INNER JOIN VW_CAR car ON car.REGISTRATION_NUM = dr_car.CAR_ID;

go
CREATE OR ALTER VIEW VW_REVIEW AS
SELECT r.ORDER_ID AS ID, r.TEXT, r.STARS, c.NAME
FROM REVIEW r
INNER JOIN [ORDER] o ON r.ORDER_ID = o.ID
INNER JOIN CLIENT c ON c.ID = o.CLIENT_ID;

go
CREATE OR ALTER VIEW VW_ACTIVE_ORDERS AS
SELECT *
FROM VW_ORDER

go
CREATE OR ALTER PROCEDURE UPDATE_ORDER_STATUS
    @p_order_id INT,
    @p_new_status INT
AS
BEGIN
    UPDATE [ORDER]
    SET STATUS = @p_new_status
    WHERE ID = @p_order_id;


    COMMIT;
END;
GO

go
CREATE OR ALTER PROCEDURE ADD_DRIVER
    @p_name NVARCHAR(255),
    @p_surname NVARCHAR(255),
    @p_license INT,
    @p_phone_number VARCHAR(20),
    @p_email NVARCHAR(255)
AS
BEGIN
    INSERT INTO DRIVER (NAME, SURNAME, LICENSE, PHONE_NUMBER, EMAIL)
    VALUES (@p_name, @p_surname, @p_license, @p_phone_number, @p_email);

    COMMIT;
END;
GO


CREATE OR ALTER PROCEDURE GET_CARS_BY_COLOR
    @p_color_id INT
AS
BEGIN
    SELECT c.REGISTRATION_NUM, b.BRAND_NAME, c.MODEL, c.YEAR
    FROM CAR c
    INNER JOIN BRAND b ON c.BRAND_ID = b.ID
    WHERE c.COLOR_ID = @p_color_id;
END;
GO
;

CREATE OR ALTER PROCEDURE ADD_REVIEW
    @p_order_id INT,
    @p_text NVARCHAR(1000),
    @p_stars INT
AS
BEGIN
    INSERT INTO REVIEW (ORDER_ID, TEXT, STARS)
    VALUES (@p_order_id, @p_text, @p_stars);

    COMMIT;
END;
GO

select * from ADD_REVIEW;

CREATE INDEX IDX_ORDER_CLIENT_ID ON [ORDER] (CLIENT_ID);
CREATE UNIQUE INDEX IDX_DRIVER_LICENSE ON DRIVER (LICENSE);
CREATE INDEX IDX_CAR_BRAND_ID ON CAR (BRAND_ID);
CREATE INDEX IDX_CLIENT_NAME_SURNAME ON CLIENT (NAME, SURNAME);

select * from VW_CAR;
select * from VW_DRIVER_CAR;
select * from VW_ORDER;

CREATE OR ALTER FUNCTION GET_ALL_BRANDS()
RETURNS TABLE
AS
RETURN (
    SELECT BRAND_NAME
    FROM BRAND
);

CREATE OR ALTER FUNCTION GET_ALL_COLORS()
RETURNS TABLE
AS
RETURN (
    SELECT COLOR_NAME
    FROM COLOR
);


CREATE OR ALTER FUNCTION GET_CAR_BY_REGISTRATION_NUM
(
    @p_registration_num INT
)
RETURNS TABLE
AS
RETURN (
    SELECT c.REGISTRATION_NUM, b.BRAND_NAME, c.MODEL, c.YEAR, cl.COLOR_NAME, c.CAPACITY
    FROM CAR c
    INNER JOIN BRAND b ON c.BRAND_ID = b.ID
    INNER JOIN COLOR cl ON c.COLOR_ID = cl.ID
    WHERE c.REGISTRATION_NUM = @p_registration_num
);
select * from GET_ALL_BRANDS();