LOAD DATA
INFILE 'D:\BD\DRIVER2.csv'
APPEND INTO TABLE Products1
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    ProductId INTEGER EXTERNAL TERMINATED BY ",",
    ProductName "UPPER(:ProductName)",
    Price "ROUND(:Price,1)" ,
    CategoryId INTEGER EXTERNAL TERMINATED BY ","
)
